<div id="js_launcher">Hi</div>
<script type="text/javascript">
require([
        'jquery',
        'jquery/ui',
        'Magento_Ui/js/modal/modal'
    ],
    function($, ui, modal) {
    var pulsestorm_launcher_menu = <?php echo $block->getJson(); ?>;
    var combined_codes = '<?php echo $block->getCombinedCodes(); ?>';
    var key_queue = [null,null];
    var menu_links      = {};
    var menu_parents    = [];
    var options = {
        type: 'popup',
        responsive: true,
        innerScroll: true,
        modalClass: 'js-launcher',
        buttons: [],
        focus: '#pulsestorm_launcher_input',
        opened: function($Event) {
            $(".modal-footer").hide();
        }
    };
    "use strict";
    $(document).ready(function(){
        $('body').on("keydown", function (e) {
            if(e.which == 40 || e.which == 38)
            {
                return;
            }
            key_queue.push(e.which);
            key_queue.shift();
            if(key_queue.join('_') == combined_codes)
            {
                openPopup();
            }
        });
        a = render_menu(pulsestorm_launcher_menu, [], 1);
        function openPopup() {
            var content = "<input type=\"search\" id=\"pulsestorm_launcher_input\" name=\"pulsestorm_launcher_input\"/>";
            content += "<div id=\"pulsestorm_launcher_results\"></div> ";
            $('#js_launcher').html(content).modal(options).modal('openModal');
            setTimeout(function(){
                var timeout_search=false;
                $('#pulsestorm_launcher_input').on('keyup', function(e){

                    if (e.which == 40) {
                        down();
                        return;
                    }

                    if (e.which == 38) {
                        up();
                        return;
                    }

                    if(e.which == 13)
                    {
                        go_to_highlighted_link();
                        return;
                    }
                    //cancel/reset interval
                    if(timeout_search)
                    {
                        clearTimeout(timeout_search);
                    }
                    /*if($('pulsestorm_launcher_input') && $('pulsestorm_launcher_input').length > 2)
                    {
                        timeout_search = setTimeout(function(){
                            var searchurl = pulsestorm_launcher_search_url.url;
                            searchurl += ('?query='+$('pulsestorm_launcher_input'));
                            p.id = 'pulsestorm_launcher_throbber';
                            $('pulsestorm_launcher_results').insert(p);

                            $.ajax({
                                url: searchurl,
                                type: "GET",
                                showLoader: true
                            }).done(function (transport) {
                                var container = new Element('div');
                                container.update(transport.responseText);
                                $('pulsestorm_launcher_throbber').remove();
                                container.getElementsBySelector('li strong').each(function(element){
                                    if(!element.parentNode)
                                    {
                                        return;
                                    }

                                    var url = $(element.parentNode).readAttribute('url');
                                    var row = '<p><a href="'+url+'">'+element.innerHTML+'</a></p>';
                                    $('pulsestorm_launcher_results').insert(row);
                                    console.log(element);
                                    //console.log(element.parentNode);
                                });
                            });

                        }, 100);
                    }*/

                    //perform instant nav/config search
                    var results = pulsestorm_launcher_search_menu($('#pulsestorm_launcher_input'));
                    if(!$(results).map)
                    {
                        $('#pulsestorm_launcher_results').html('');
                        return;
                    }
                    var html = $.map(results, function(e){
                        var url = e['url'];
                        return "<p><a href=\""+url+"\">" + e['label-full'] + "</a></p>";
                    });
                    $('#pulsestorm_launcher_results').html(html.join(''));
                });

            }, 10);

        }

        function render_menu(o,a,depth)
        {
            Object.keys(o).forEach(function(item){
                var menu = o[item];
                if(menu.url && menu.url != '#')
                {
                    register_link(menu.label, menu.url);
                }

                a.push(Array(depth).join('-') + item);

                if(menu.children)
                {
                    menu_parents.push(menu.label);
                    render_menu(menu.children,a,depth+1);
                    menu_parents.pop();
                }
            });
            return a;
        }

        function pulsestorm_launcher_search_menu(string)
        {
            if(!string)
            {
                return menu_links;
            }
            string = $(string).val().toString().toLowerCase();
            var returnedKeys = $.grep(Object.keys(menu_links), function (element, index) {
                return (element.indexOf(string) != -1) ? element : false ;
            });
            return returnedKeys.map(function(v){
                return menu_links[v];
            });
        }

        function register_link(label, url)
        {
            var pre = '';
            if(menu_parents.length > 0)
            {
                pre = menu_parents.join(' - ');
                pre += ' - ';
            }
            menu_links[(pre+label).toLowerCase()] = {
                'url':url,
                'label':label,
                'label-full':pre+label};
        }

        function up()
        {
            var elements = $('#pulsestorm_launcher_results').children("p");
            var i = get_selected_highlight_index();
            if(i > 0)
            {
                $(elements[i]).removeClass('highlight');
                $(elements[i-1]).addClass('highlight');
            }
            scrollResults();
        }

        function down()
        {
            var elements = $('#pulsestorm_launcher_results').children("p");
            var i = get_selected_highlight_index();
            if(i+1 != elements.length)
            {
                if(elements[i])
                {
                    $(elements[i]).removeClass('highlight');
                }
                $(elements[i+1]).addClass('highlight');
            }
            scrollResults();
        }

        function go_to_highlighted_link()
        {
            var a    = $('#pulsestorm_launcher_results p.highlight').children("a");
            if(!a || !a[0])
            {
                return;
            }
            document.location = a[0].href;
        }

        function get_selected_highlight_index()
        {
            var elements = $('#pulsestorm_launcher_results').children("p");
            var found = false;
            for(var i=0;i<elements.length;i++)
            {
                if($(elements[i]).hasClass('highlight'))
                {
                    found = true;
                    break;
                }
            }

            return found ? i : -1
        }

        function scrollResults()
        {
            var $container = $("#pulsestorm_launcher_results");
            var $scrollTo = $('.highlight');

            $container.animate({scrollTop: $scrollTo.offset().top - $container.offset().top + $container.scrollTop(), scrollLeft: 0},100);
        }
    });
});
</script>
<style>
    #pulsestorm_launcher_input {
        width: 90%;
        line-height: 40px;
        font-size: 18px;
        text-indent: 10px;
        position: fixed;
    }
    #pulsestorm_launcher_results p {
        font-size: 18px;
        padding: 3px 10px;
    }
    #pulsestorm_launcher_results {
        padding-top: 50px;
    }
    #pulsestorm_launcher_results p.highlight {
        background-color: #c2e4efbf;
        line-height: 34px
    }
    #js_launcher {
        width: 96%;
        position: relative;
    }
</style>