<div id="js_launcher">
    <input placeholder="<?= __("Type in where you want to go") ?>" type="search" id="search_box" name="search_box" />
    <div id="search_results"></div>
</div>
<script type="text/x-magento-init">
{
    "#js_launcher": {
        "js-launcher": {
            "searchbox":"#search_box",
            "searchResultsBox":"#search_results",
            "menuJson":<?= $block->getJson(); ?>,
            "keyCodes":"<?= $block->getCombinedCodes(); ?>",
            "searchUrl":"<?= $block->getSearchUrl(); ?>",
            "launcherPopup":"#js_launcher"
        }
    }
}
</script>
